services:
  backend:
    image: node:23
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    depends_on:
      - db
      - redis
    command: >
      sh -c "apt-get update -y && apt-get install -y openssl && npm install && npm run start:dev"


#  frontend:
#    image: node:23-slim
#    working_dir: /app
#    volumes:
#      - ./frontend:/app
#    ports:
#      - "4000:4000"
#    environment:
#      - API_BASE_URL=http://backend:3000
#    depends_on:
#      - backend
#    command: >
#      sh -c "npm install && npm run dev"

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: novel_tracker
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db-data:
